### ISSUE TITLE
target images folder in demo.py

### ISSUE THREAD

**Issue by rashminair1995** [AliaksandrSiarohin/pose-gan#17]
what images to put in target images folder in demo.py? and what do you mean by  'For target images use kp from previous frame if not detected'?

**Comment by AliaksandrSiarohin** [comment]
I forget to upload target images, sorry. (Now they are on master) In this particular demo I try to create a video sequence. I use the command:
`python demo.py --dataset prw --warp_skip mask --generator_checkpoint generator-warp-mask-nn3-cl12.h5 --use_bg 1`.
Note that checkpoint is for prw dataset.

Since I am trying to generate a video: the position of key-points should not change much between consecutive frames. If keypoint is not detected, I take the keypoint from the previous frame.
